#!/bin/bash
###
# Updating apt cache
###
apt-get update
###
# Installing fpm dependencies
###
apt-get install --yes \
  ruby-dev \
  gcc \
  make
###
# Instlling fpm
###
gem install --no-ri --no-rdoc fpm
